Database: https://www.kaggle.com/datasets/bkcoban/retail-transaction-dataset

Very simple dataset with 30,000 entries that follows the style seen in the lecture

In [ ]:
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)
#fix for an error with mlxtend package showing depreceation warnings
#run before running code below

In [ ]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
df = pd.read_csv('products.csv')
df = df[['Products']]
df.head()
#reads products.csv and takes the products column to try and match what we see in the example
#must download csv from kaggle and use google colabs upload function to upload

                                            Products
0  Dish Sponge, Flatbread with Meat, Chips, Orang...
1         Onion, Juice, Flatbread with Meat, Chicken
2            Egg, Flatbread with Meat, Banana, Pizza
3  Ice Cream, Soda, Orange, Potato, Cereal, Choco...
4  Ice Cream, Soap, Shampoo, Chicken, Banana, Bea...

In [ ]:
df.shape
#30,000 entries in products column

(30000, 1)

In [ ]:
data=list(df['Products'].apply(lambda x:x.split(",")))
data
#splits strings into a list using comma as delimiter

[['Dish Sponge',
  ' Flatbread with Meat',
  ' Chips',
  ' Orange',
  ' Butter',
  ' Sausage',
  ' Cucumber',
  ' Rice',
  ' Ice Cream'],
 ['Onion', ' Juice', ' Flatbread with Meat', ' Chicken'],
 ['Egg', ' Flatbread with Meat', ' Banana', ' Pizza'],
 ['Ice Cream',
  ' Soda',
  ' Orange',
  ' Potato',
  ' Cereal',
  ' Chocolate',
  ' Cracker'],
 ['Ice Cream',
  ' Soap',
  ' Shampoo',
  ' Chicken',
  ' Banana',
  ' Beans',
  ' Cheese'],
 ['Juice',
  ' Shampoo',
  ' Bread',
  ' Flatbread with Meat',
  ' Cracker',
  ' Cucumber',
  ' Fish'],
 ['Soda',
  ' Chocolate',
  ' Beans',
  ' Juice',
  ' Orange',
  ' Bread',
  ' Tomato',
  ' Yogurt',
  ' Minced Meat'],
 ['Cookie',
  ' Cereal',
  ' Sausage',
  ' Chips',
  ' Chocolate',
  ' Lentil',
  ' Water',
  ' Egg',
  ' Cheese'],
 ['Soda', ' Rice', ' Soap', ' Chickpeas'],
 ['Orange', ' Minced Meat', ' Chickpeas'],
 ['Milk',
  ' Minced Meat',
  ' Chips',
  ' Chicken',
  ' Onion',
  ' Cheese',
  ' Chickpeas',
  ' Cereal'],
 ['Dish Sponge', ' Onion', ' Detergent', ' Egg', ' Chicken'],
 ['Sausage', ' Strawberry', ' Cracker', ' Pizza'],
 ['Cereal', ' Minced Meat', ' Banana', ' Dish Sponge', ' Orange'],
 ['Yogurt', ' Dish Sponge', ' Butter', ' Cookie'],
 ['Potato', ' Chicken', ' Cucumber', ' Soda', ' Butter', ' Juice'],
 ['Minced Meat',
  ' Cereal',
  ' Flatbread with Meat',
  ' Onion',
  ' Honey',
  ' Lentil',
  ' Cucumber',
  ' Orange',
  ' Cola',
  ' Ice Cream'],
 ['Flatbread with Meat', ' Juice', ' Cola'],
 ['Cracker',
  ' Sausage',
  ' Dumpling',
  ' Cookie',
  ' Detergent',
  ' Chickpeas',
  ' Pizza',
  ' Banana',
  ' Cereal'],
 ['Cracker',
  ' Chicken',
  ' Tomato',
  ' Cola',
  ' Shampoo',
  ' Cookie',
  ' Minced Meat',
  ' Yogurt'],
 ['Lentil', ' Chicken', ' Yogurt', ' Onion'],
 ['Minced Meat', ' Ice Cream', ' Soap', ' Cookie'],
 ['Tomato', ' Apple', ' Ice Cream', ' Honey', ' Fish', ' Soda', ' Yogurt'],
 ['Dish Sponge', ' Minced Meat', ' Cola', ' Juice', ' Flatbread with Meat'],
 ['Strawberry',
  ' Egg',
  ' Juice',
  ' Pizza',
  ' Beans',
  ' Chickpeas',
  ' Cheese',
  ' Cola',
  ' Minced Meat',
  ' Cracker'],
 ['Chocolate',
  ' Flatbread with Meat',
  ' Detergent',
  ' Shampoo',
  ' Cucumber',
  ' Cola',
  ' Sausage',
  ' Cheese',
  ' Potato'],
 ['Pizza',
  ' Bread',
  ' Potato',
  ' Beans',
  ' Butter',
  ' Cracker',
  ' Chips',
  ' Rice',
  ' Minced Meat'],
 ['Lentil',
  ' Cola',
  ' Shampoo',
  ' Juice',
  ' Strawberry',
  ' Bread',
  ' Onion',
  ' Cucumber'],
 ['Fish', ' Potato', ' Cereal', ' Cookie'],
 ['Banana',
  ' Cheese',
  ' Chocolate',
  ' Butter',
  ' Milk',
  ' Minced Meat',
  ' Honey',
  ' Soda',
  ' Cereal'],
 ['Egg', ' Chocolate', ' Cucumber', ' Detergent'],
 ['Egg',
  ' Honey',
  ' Dish Sponge',
  ' Cracker',
  ' Chickpeas',
  ' Minced Meat',
  ' Rice',
  ' Potato'],
 ['Chips', ' Flatbread with Meat', ' Ice Cream', ' Egg', ' Chicken'],
 ['Fish',
  ' Chickpeas',
  ' Potato',
  ' Sausage',
  ' Flatbread with Meat',
  ' Banana',
  ' Shampoo',
  ' Beans',
  ' Cookie',
  ' Cheese'],
 ['Chickpeas', ' Rice', ' Dumpling', ' Beans', ' Yogurt', ' Cookie'],
 ['Tomato',
  ' Water',
  ' Pizza',
  ' Honey',
  ' Shampoo',
  ' Lentil',
  ' Detergent',
  ' Chips',
  ' Cracker',
  ' Butter'],
 ['Milk',
  ' Dish Sponge',
  ' Strawberry',
  ' Ice Cream',
  ' Chickpeas',
  ' Shampoo',
  ' Soda',
  ' Cola',
  ' Cheese',
  ' Egg'],
 ['Pizza', ' Water', ' Yogurt', ' Potato', ' Cracker', ' Rice'],
 ['Chicken',
  ' Dumpling',
  ' Tomato',
  ' Lentil',
  ' Cucumber',
  ' Cereal',
  ' Cookie',
  ' Orange'],
 ['Potato', ' Cookie', ' Orange', ' Egg', ' Beans', ' Ice Cream'],
 ['Beans', ' Cereal', ' Butter', ' Honey'],
 ['Dumpling', ' Chocolate', ' Onion', ' Soap'],
 ['Sausage',
  ' Beans',
  ' Ice Cream',
  ' Chocolate',
  ' Shampoo',
  ' Juice',
  ' Dish Sponge'],
 ['Cookie',
  ' Sausage',
  ' Shampoo',
  ' Egg',
  ' Rice',
  ' Water',
  ' Dumpling',
  ' Onion'],
 ['Yogurt',
  ' Cereal',
  ' Sausage',
  ' Cheese',
  ' Bread',
  ' Juice',
  ' Flatbread with Meat',
  ' Strawberry',
  ' Ice Cream'],
 ['Chickpeas', ' Juice', ' Orange'],
 ['Cracker', ' Tomato', ' Beans', ' Orange', ' Ice Cream', ' Lentil'],
 ['Chips', ' Potato', ' Honey', ' Chocolate'],
 ['Banana',
  ' Lentil',
  ' Apple',
  ' Cola',
  ' Pizza',
  ' Shampoo',
  ' Juice',
  ' Dish Sponge',
  ' Sausage'],
 ['Dumpling',
  ' Onion',
  ' Cereal',
  ' Butter',
  ' Detergent',
  ' Banana',
  ' Water',
  ' Chocolate',
  ' Cucumber',
  ' Milk'],
 ['Egg', ' Strawberry', ' Cracker', ' Dish Sponge', ' Potato'],
 ['Sausage', ' Strawberry', ' Yogurt', ' Chicken'],
 ['Ice Cream', ' Tomato', ' Rice'],
 ['Bread', ' Onion', ' Minced Meat'],
 ['Bread', ' Chocolate', ' Sausage', ' Fish', ' Cookie', ' Dumpling'],
 ['Cheese',
  ' Chicken',
  ' Dumpling',
  ' Flatbread with Meat',
  ' Cereal',
  ' Milk',
  ' Minced Meat',
  ' Tomato'],
 ['Flatbread with Meat',
  ' Minced Meat',
  ' Yogurt',
  ' Apple',
  ' Orange',
  ' Chicken',
  ' Egg'],
 ['Potato',
  ' Cucumber',
  ' Soda',
  ' Juice',
  ' Beans',
  ' Cereal',
  ' Cheese',
  ' Bread',
  ' Lentil',
  ' Chicken'],
 ['Honey', ' Potato', ' Pizza', ' Beans', ' Cola', ' Fish', ' Lentil'],
 ['Banana', ' Dumpling', ' Cheese', ' Milk', ' Apple', ' Beans', ' Cereal'],
 ['Detergent',
  ' Chips',
  ' Strawberry',
  ' Chickpeas',
  ' Bread',
  ' Rice',
  ' Milk',
  ' Onion',
  ' Yogurt',
  ' Cola'],
 ['Strawberry',
  ' Cola',
  ' Cereal',
  ' Cracker',
  ' Rice',
  ' Lentil',
  ' Beans',
  ' Ice Cream',
  ' Dumpling',
  ' Yogurt'],
 ['Soda', ' Strawberry', ' Minced Meat'],
 ['Cookie', ' Potato', ' Cheese', ' Beans', ' Chocolate', ' Shampoo', ' Egg'],
 ['Potato', ' Butter', ' Ice Cream'],
 ['Detergent', ' Apple', ' Tomato', ' Water', ' Strawberry', ' Rice'],
 ['Water',
  ' Soap',
  ' Dumpling',
  ' Chickpeas',
  ' Chocolate',
  ' Cucumber',
  ' Minced Meat',
  ' Beans',
  ' Strawberry',
  ' Pizza'],
 ['Bread', ' Dumpling', ' Strawberry'],
 ['Tomato',
  ' Orange',
  ' Chips',
  ' Water',
  ' Beans',
  ' Dumpling',
  ' Cookie',
  ' Chocolate'],
 ['Minced Meat',
  ' Lentil',
  ' Cracker',
  ' Butter',
  ' Rice',
  ' Sausage',
  ' Yogurt',
  ' Cookie',
  ' Tomato'],
 ['Cola', ' Banana', ' Chicken', ' Cereal', ' Soda', ' Beans', ' Onion'],
 ['Chips', ' Soda', ' Chickpeas', ' Soap', ' Honey', ' Chocolate'],
 ['Pizza',
  ' Yogurt',
  ' Egg',
  ' Dish Sponge',
  ' Chickpeas',
  ' Orange',
  ' Water',
  ' Cracker',
  ' Cola'],
 ['Bread',
  ' Soda',
  ' Honey',
  ' Chocolate',
  ' Egg',
  ' Apple',
  ' Lentil',
  ' Pizza',
  ' Orange',
  ' Rice'],
 ['Dish Sponge', ' Lentil', ' Apple', ' Cheese'],
 ['Minced Meat',
  ' Cereal',
  ' Tomato',
  ' Chocolate',
  ' Egg',
  ' Banana',
  ' Onion',
  ' Flatbread with Meat',
  ' Juice',
  ' Soap'],
 ['Strawberry', ' Onion', ' Soda', ' Chicken', ' Yogurt'],
 ['Fish', ' Honey', ' Egg'],
 ['Water',
  ' Butter',
  ' Honey',
  ' Cucumber',
  ' Egg',
  ' Soda',
  ' Milk',
  ' Apple',
  ' Strawberry',
  ' Cookie',
  ' Cereal'],
 ['Ice Cream',
  ' Sausage',
  ' Cucumber',
  ' Milk',
  ' Soap',
  ' Apple',
  ' Strawberry',
  ' Orange',
  ' Water'],
 ['Pizza', ' Water', ' Chocolate', ' Detergent', ' Soap'],
 ['Pizza', ' Bread', ' Rice', ' Ice Cream', ' Dumpling', ' Sausage'],
 ['Apple', ' Strawberry', ' Yogurt', ' Cucumber', ' Rice'],
 ['Cereal', ' Rice', ' Yogurt'],
 ['Ice Cream',
  ' Egg',
  ' Chips',
  ' Juice',
  ' Strawberry',
  ' Onion',
  ' Chickpeas',
  ' Apple'],
 ['Cucumber', ' Ice Cream', ' Sausage'],
 ['Cereal',
  ' Ice Cream',
  ' Shampoo',
  ' Flatbread with Meat',
  ' Butter',
  ' Banana',
  ' Strawberry',
  ' Egg'],
 ['Fish',
  ' Soap',
  ' Detergent',
  ' Lentil',
  ' Yogurt',
  ' Sausage',
  ' Tomato',
  ' Cookie',
  ' Cracker',
  ' Apple'],
 ['Cheese',
  ' Ice Cream',
  ' Bread',
  ' Apple',
  ' Orange',
  ' Shampoo',
  ' Lentil',
  ' Honey'],
 ['Yogurt',
  ' Pizza',
  ' Cheese',
  ' Cola',
  ' Dumpling',
  ' Minced Meat',
  ' Chips'],
 ['Dumpling', ' Cracker', ' Cookie', ' Strawberry', ' Rice'],
 ['Orange', ' Minced Meat', ' Rice', ' Potato'],
 ['Soap',
  ' Chips',
  ' Juice',
  ' Rice',
  ' Cola',
  ' Ice Cream',
  ' Chocolate',
  ' Minced Meat',
  ' Orange',
  ' Cucumber'],
 ['Lentil', ' Butter', ' Potato', ' Soda', ' Chicken'],
 ['Cracker', ' Chickpeas', ' Onion', ' Milk', ' Shampoo', ' Egg'],
 ['Bread',
  ' Milk',
  ' Dish Sponge',
  ' Dumpling',
  ' Cola',
  ' Soda',
  ' Cookie',
  ' Cereal'],
 ['Cookie',
  ' Cheese',
  ' Apple',
  ' Detergent',
  ' Strawberry',
  ' Soda',
  ' Banana',
  ' Tomato',
  ' Chickpeas',
  ' Potato'],
 ['Honey',
  ' Apple',
  ' Potato',
  ' Cola',
  ' Soda',
  ' Dumpling',
  ' Ice Cream',
  ' Chips',
  ' Dish Sponge',
  ' Flatbread with Meat'],
 ['Chocolate', ' Sausage', ' Pizza', ' Shampoo', ' Dumpling'],
 ['Fish',
  ' Detergent',
  ' Honey',
  ' Water',
  ' Flatbread with Meat',
  ' Cucumber'],
 ['Orange', ' Chips', ' Cheese', ' Cracker'],
 ['Potato',
  ' Tomato',
  ' Flatbread with Meat',
  ' Dumpling',
  ' Honey',
  ' Soap',
  ' Detergent',
  ' Dish Sponge'],
 ['Chips', ' Shampoo', ' Soda'],
 ['Cracker',
  ' Banana',
  ' Soap',
  ' Cereal',
  ' Onion',
  ' Milk',
  ' Detergent',
  ' Beans'],
 ['Cheese', ' Soap', ' Milk'],
 ['Cereal',
  ' Yogurt',
  ' Beans',
  ' Fish',
  ' Banana',
  ' Cola',
  ' Minced Meat',
  ' Strawberry',
  ' Sausage',
  ' Egg'],
 ['Apple', ' Soda', ' Minced Meat', ' Dish Sponge', ' Rice', ' Sausage'],
 ['Chips', ' Orange', ' Yogurt', ' Rice', ' Shampoo', ' Soap'],
 ['Cracker',
  ' Soda',
  ' Flatbread with Meat',
  ' Onion',
  ' Tomato',
  ' Minced Meat',
  ' Bread',
  ' Apple',
  ' Cheese',
  ' Yogurt'],
 ['Strawberry', ' Juice', ' Cheese', ' Chips', ' Fish', ' Cookie'],
 ['Cheese',
  ' Minced Meat',
  ' Water',
  ' Dish Sponge',
  ' Dumpling',
  ' Soda',
  ' Yogurt',
  ' Honey',
  ' Fish'],
 ['Cola', ' Fish', ' Bread', ' Chocolate', ' Juice', ' Soap'],
 ['Tomato', ' Apple', ' Chickpeas'],
 ['Cracker', ' Dumpling', ' Soda', ' Milk', ' Egg', ' Chocolate', ' Lentil'],
 ['Apple', ' Honey', ' Chickpeas', ' Soap'],
 ['Orange',
  ' Yogurt',
  ' Soda',
  ' Cracker',
  ' Honey',
  ' Chips',
  ' Soap',
  ' Egg'],
 ['Butter',
  ' Lentil',
  ' Tomato',
  ' Ice Cream',
  ' Onion',
  ' Pizza',
  ' Sausage',
  ' Cracker',
  ' Cola'],
 ['Pizza', ' Butter', ' Cereal', ' Soda', ' Lentil'],
 ['Potato',
  ' Flatbread with Meat',
  ' Dumpling',
  ' Chickpeas',
  ' Strawberry',
  ' Onion',
  ' Pizza',
  ' Fish'],
 ['Milk', ' Ice Cream', ' Yogurt', ' Juice', ' Apple', ' Cola', ' Cereal'],
 ['Sausage', ' Cookie', ' Cereal'],
 ['Orange', ' Rice', ' Egg', ' Onion', ' Soda'],
 ['Pizza', ' Dumpling', ' Detergent'],
 ['Potato', ' Dumpling', ' Yogurt', ' Sausage', ' Banana', ' Chocolate'],
 ['Water',
  ' Juice',
  ' Cucumber',
  ' Tomato',
  ' Chicken',
  ' Onion',
  ' Pizza',
  ' Rice',
  ' Detergent',
  ' Butter'],
 ['Yogurt',
  ' Onion',
  ' Chickpeas',
  ' Chips',
  ' Strawberry',
  ' Juice',
  ' Detergent',
  ' Butter',
  ' Dumpling',
  ' Cola'],
 ['Water',
  ' Apple',
  ' Butter',
  ' Chickpeas',
  ' Tomato',
  ' Detergent',
  ' Pizza'],
 ['Milk',
  ' Shampoo',
  ' Minced Meat',
  ' Beans',
  ' Pizza',
  ' Chicken',
  ' Tomato',
  ' Apple',
  ' Dish Sponge'],
 ['Sausage', ' Banana', ' Soap', ' Cola'],
 ['Sausage',
  ' Strawberry',
  ' Chocolate',
  ' Dumpling',
  ' Chicken',
  ' Chickpeas',
  ' Tomato',
  ' Juice'],
 ['Chocolate', ' Milk', ' Juice'],
 ['Milk', ' Potato', ' Chips', ' Dumpling'],
 ['Cheese', ' Honey', ' Potato', ' Sausage'],
 ['Yogurt',
  ' Strawberry',
  ' Pizza',
  ' Rice',
  ' Egg',
  ' Juice',
  ' Lentil',
  ' Onion',
  ' Potato'],
 ['Butter', ' Banana', ' Shampoo', ' Chips', ' Cucumber'],
 ['Tomato', ' Ice Cream', ' Cereal', ' Chips', ' Chicken', ' Beans'],
 ['Cereal',
  ' Chickpeas',
  ' Soap',
  ' Pizza',
  ' Chicken',
  ' Water',
  ' Egg',
  ' Honey'],
 ['Tomato', ' Cola', ' Beans', ' Fish', ' Minced Meat'],
 ['Orange', ' Cucumber', ' Honey'],
 ['Apple',
  ' Cheese',
  ' Milk',
  ' Cookie',
  ' Lentil',
  ' Cracker',
  ' Detergent',
  ' Orange',
  ' Minced Meat',
  ' Cereal'],
 ['Bread',
  ' Rice',
  ' Water',
  ' Chickpeas',
  ' Flatbread with Meat',
  ' Soap',
  ' Pizza',
  ' Potato',
  ' Detergent',
  ' Dumpling'],
 ['Chips',
  ' Soda',
  ' Rice',
  ' Dish Sponge',
  ' Bread',
  ' Shampoo',
  ' Potato',
  ' Chocolate'],
 ['Honey',
  ' Onion',
  ' Potato',
  ' Soda',
  ' Cucumber',
  ' Tomato',
  ' Chips',
  ' Cola'],
 ['Fish', ' Juice', ' Lentil'],
 ['Apple', ' Sausage', ' Pizza', ' Chips', ' Cookie', ' Bread', ' Juice'],
 ['Chips', ' Apple', ' Potato', ' Yogurt', ' Minced Meat', ' Honey'],
 ['Flatbread with Meat',
  ' Honey',
  ' Chickpeas',
  ' Yogurt',
  ' Dumpling',
  ' Cheese',
  ' Cracker',
  ' Detergent',
  ' Ice Cream',
  ' Potato'],
 ['Chickpeas', ' Chocolate', ' Egg'],
 ['Chocolate', ' Butter', ' Cheese', ' Lentil', ' Honey', ' Rice', ' Bread'],
 ['Dish Sponge',
  ' Milk',
  ' Onion',
  ' Minced Meat',
  ' Beans',
  ' Sausage',
  ' Soda',
  ' Honey',
  ' Cereal'],
 ['Shampoo',
  ' Beans',
  ' Strawberry',
  ' Chicken',
  ' Orange',
  ' Dumpling',
  ' Pizza',
  ' Detergent',
  ' Minced Meat',
  ' Chips'],
 ['Dumpling', ' Rice', ' Strawberry', ' Banana', ' Detergent', ' Minced Meat'],
 ['Yogurt',
  ' Honey',
  ' Beans',
  ' Chocolate',
  ' Detergent',
  ' Fish',
  ' Cola',
  ' Dumpling'],
 ['Strawberry', ' Detergent', ' Chicken', ' Egg'],
 ['Beans',
  ' Bread',
  ' Chocolate',
  ' Orange',
  ' Soda',
  ' Egg',
  ' Honey',
  ' Flatbread with Meat',
  ' Cereal'],
 ['Dish Sponge', ' Dumpling', ' Cracker', ' Cheese'],
 ['Soda',
  ' Beans',
  ' Strawberry',
  ' Cracker',
  ' Cucumber',
  ' Milk',
  ' Cereal',
  ' Chips'],
 ['Yogurt', ' Lentil', ' Flatbread with Meat'],
 ['Milk', ' Chocolate', ' Cola', ' Sausage', ' Shampoo'],
 ['Tomato',
  ' Rice',
  ' Banana',
  ' Water',
  ' Soda',
  ' Cookie',
  ' Chips',
  ' Cola',
  ' Chicken'],
 ['Chicken', ' Cola', ' Cucumber', ' Chocolate', ' Lentil'],
 ['Honey', ' Cereal', ' Yogurt', ' Dish Sponge', ' Rice'],
 ['Onion',
  ' Chickpeas',
  ' Bread',
  ' Egg',
  ' Cucumber',
  ' Minced Meat',
  ' Potato'],
 ['Bread', ' Chocolate', ' Fish', ' Cracker', ' Cookie'],
 ['Cucumber',
  ' Orange',
  ' Apple',
  ' Minced Meat',
  ' Lentil',
  ' Soda',
  ' Chips'],
 ['Bread', ' Cracker', ' Minced Meat', ' Apple'],
 ['Butter',
  ' Water',
  ' Egg',
  ' Detergent',
  ' Banana',
  ' Strawberry',
  ' Soap',
  ' Rice'],
 ['Strawberry',
  ' Bread',
  ' Shampoo',
  ' Soap',
  ' Beans',
  ' Sausage',
  ' Lentil',
  ' Soda',
  ' Fish',
  ' Chocolate'],
 ['Shampoo', ' Lentil', ' Soap', ' Cookie', ' Banana'],
 ['Lentil', ' Tomato', ' Cereal', ' Detergent', ' Strawberry', ' Cucumber'],
 ['Shampoo', ' Detergent', ' Cereal', ' Beans', ' Chickpeas'],
 ['Butter',
  ' Chips',
  ' Flatbread with Meat',
  ' Ice Cream',
  ' Fish',
  ' Onion',
  ' Pizza',
  ' Milk'],
 ['Butter',
  ' Detergent',
  ' Bread',
  ' Dish Sponge',
  ' Chickpeas',
  ' Banana',
  ' Juice',
  ' Cheese',
  ' Shampoo',
  ' Tomato'],
 ['Cola',
  ' Juice',
  ' Fish',
  ' Cheese',
  ' Cookie',
  ' Flatbread with Meat',
  ' Soda'],
 ['Lentil',
  ' Chips',
  ' Butter',
  ' Ice Cream',
  ' Cheese',
  ' Cucumber',
  ' Cola',
  ' Dumpling'],
 ['Orange', ' Juice', ' Soda', ' Water', ' Apple'],
 ['Ice Cream',
  ' Honey',
  ' Rice',
  ' Chicken',
  ' Chocolate',
  ' Strawberry',
  ' Shampoo',
  ' Detergent',
  ' Minced Meat'],
 ['Tomato', ' Cheese', ' Cucumber'],
 ['Chickpeas',
  ' Tomato',
  ' Honey',
  ' Chocolate',
  ' Yogurt',
  ' Chips',
  ' Beans'],
 ['Lentil',
  ' Chickpeas',
  ' Cracker',
  ' Soap',
  ' Juice',
  ' Chocolate',
  ' Tomato',
  ' Pizza',
  ' Cola',
  ' Onion'],
 ['Honey', ' Strawberry', ' Yogurt'],
 ['Bread',
  ' Ice Cream',
  ' Apple',
  ' Dumpling',
  ' Milk',
  ' Dish Sponge',
  ' Shampoo',
  ' Cucumber',
  ' Honey',
  ' Beans'],
 ['Detergent', ' Rice', ' Minced Meat'],
 ['Yogurt', ' Bread', ' Tomato', ' Cracker', ' Pizza', ' Cucumber', ' Soda'],
 ['Dish Sponge',
  ' Water',
  ' Ice Cream',
  ' Orange',
  ' Honey',
  ' Yogurt',
  ' Minced Meat'],
 ['Minced Meat', ' Fish', ' Water', ' Onion', ' Yogurt', ' Apple'],
 ['Cola',
  ' Dish Sponge',
  ' Pizza',
  ' Potato',
  ' Cucumber',
  ' Beans',
  ' Bread',
  ' Lentil'],
 ['Cucumber', ' Milk', ' Dish Sponge', ' Cola', ' Beans', ' Cereal'],
 ['Orange',
  ' Yogurt',
  ' Shampoo',
  ' Lentil',
  ' Bread',
  ' Cracker',
  ' Cheese',
  ' Chickpeas',
  ' Juice',
  ' Chocolate'],
 ['Cereal',
  ' Milk',
  ' Pizza',
  ' Rice',
  ' Soap',
  ' Banana',
  ' Potato',
  ' Cucumber',
  ' Beans'],
 ['Sausage', ' Fish', ' Lentil'],
 ['Water', ' Tomato', ' Cookie', ' Cola', ' Chickpeas'],
 ['Water',
  ' Banana',
  ' Soap',
  ' Flatbread with Meat',
  ' Fish',
  ' Lentil',
  ' Tomato',
  ' Egg'],
 ['Dish Sponge', ' Shampoo', ' Cookie', ' Honey', ' Chips', ' Cola'],
 ['Bread', ' Water', ' Beans', ' Dumpling'],
 ['Rice',
  ' Cheese',
  ' Water',
  ' Yogurt',
  ' Fish',
  ' Minced Meat',
  ' Strawberry',
  ' Onion'],
 ['Potato',
  ' Cola',
  ' Yogurt',
  ' Detergent',
  ' Rice',
  ' Cheese',
  ' Shampoo',
  ' Strawberry',
  ' Milk',
  ' Dish Sponge'],
 ['Soap', ' Juice', ' Flatbread with Meat', ' Chips'],
 ['Strawberry',
  ' Apple',
  ' Chickpeas',
  ' Soap',
  ' Flatbread with Meat',
  ' Potato',
  ' Butter',
  ' Chicken',
  ' Juice',
  ' Sausage'],
 ['Chickpeas',
  ' Cookie',
  ' Potato',
  ' Fish',
  ' Sausage',
  ' Lentil',
  ' Minced Meat',
  ' Cheese'],
 ['Cola', ' Shampoo', ' Banana'],
 ['Bread', ' Soda', ' Cucumber', ' Cola', ' Honey', ' Sausage', ' Potato'],
 ['Tomato', ' Ice Cream', ' Apple'],
 ['Water', ' Potato', ' Chickpeas'],
 ['Banana',
  ' Chips',
  ' Dumpling',
  ' Beans',
  ' Cookie',
  ' Egg',
  ' Detergent',
  ' Strawberry',
  ' Honey',
  ' Cola'],
 ['Cookie',
  ' Butter',
  ' Minced Meat',
  ' Dish Sponge',
  ' Cracker',
  ' Detergent',
  ' Beans',
  ' Soda',
  ' Chickpeas',
  ' Water'],
 ['Shampoo',
  ' Rice',
  ' Cheese',
  ' Fish',
  ' Juice',
  ' Water',
  ' Ice Cream',
  ' Honey'],
 ['Chips', ' Detergent', ' Ice Cream', ' Tomato', ' Cracker'],
 ['Orange', ' Ice Cream', ' Flatbread with Meat', ' Chips', ' Cracker'],
 ['Chocolate', ' Soda', ' Onion', ' Juice', ' Cookie', ' Lentil', ' Cereal'],
 ['Bread',
  ' Water',
  ' Rice',
  ' Cereal',
  ' Lentil',
  ' Chips',
  ' Yogurt',
  ' Minced Meat',
  ' Soap'],
 ['Bread', ' Cookie', ' Flatbread with Meat', ' Dish Sponge', ' Cola'],
 ['Egg', ' Milk', ' Chips', ' Soda', ' Apple', ' Cheese', ' Cereal'],
 ['Cereal',
  ' Dumpling',
  ' Soap',
  ' Minced Meat',
  ' Chocolate',
  ' Butter',
  ' Honey',
  ' Onion',
  ' Chicken',
  ' Chickpeas'],
 ['Soda',
  ' Chicken',
  ' Rice',
  ' Honey',
  ' Butter',
  ' Juice',
  ' Cola',
  ' Dish Sponge',
  ' Egg'],
 ['Cheese', ' Ice Cream', ' Cereal', ' Cookie', ' Cracker'],
 ['Butter', ' Egg', ' Chips', ' Juice'],
 ['Milk', ' Cheese', ' Orange', ' Yogurt'],
 ['Honey',
  ' Detergent',
  ' Beans',
  ' Milk',
  ' Cheese',
  ' Dish Sponge',
  ' Rice',
  ' Fish',
  ' Butter',
  ' Juice',
  ' Cereal'],
 ['Detergent', ' Chicken', ' Banana'],
 ['Egg', ' Chocolate', ' Cola', ' Strawberry', ' Dumpling'],
 ['Strawberry',
  ' Milk',
  ' Dumpling',
  ' Pizza',
  ' Rice',
  ' Soda',
  ' Orange',
  ' Chicken',
  ' Juice'],
 ['Juice', ' Beans', ' Yogurt'],
 ['Dish Sponge', ' Cola', ' Ice Cream', ' Dumpling', ' Shampoo', ' Fish'],
 ['Flatbread with Meat', ' Cookie', ' Cola', ' Water', ' Chickpeas', ' Juice'],
 ['Chickpeas', ' Tomato', ' Rice', ' Bread', ' Cola', ' Strawberry'],
 ['Cookie',
  ' Apple',
  ' Chips',
  ' Soda',
  ' Soap',
  ' Juice',
  ' Beans',
  ' Pizza',
  ' Onion'],
 ['Bread',
  ' Water',
  ' Chocolate',
  ' Dish Sponge',
  ' Milk',
  ' Honey',
  ' Cheese',
  ' Potato',
  ' Cereal'],
 ['Egg',
  ' Apple',
  ' Chickpeas',
  ' Flatbread with Meat',
  ' Cookie',
  ' Butter',
  ' Yogurt',
  ' Water',
  ' Fish'],
 ['Water',
  ' Flatbread with Meat',
  ' Soap',
  ' Apple',
  ' Strawberry',
  ' Dish Sponge',
  ' Milk',
  ' Butter',
  ' Detergent',
  ' Cereal'],
 ['Minced Meat', ' Potato', ' Cracker'],
 ['Water', ' Onion', ' Cheese'],
 ['Onion', ' Apple', ' Cola', ' Strawberry', ' Dumpling', ' Cucumber'],
 ['Bread', ' Strawberry', ' Butter', ' Detergent'],
 ['Shampoo',
  ' Juice',

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
a=TransactionEncoder()
a_data=a.fit(data).transform(data)
df=pd.DataFrame(a_data, columns=a.columns_)
df=df.astype(int)
df
#one hot encoding to label items that appear in each transaction as 1 and empty ones 0

,Apple,Banana,Beans,Bread,Butter,Cereal,Cheese,Chicken,Chickpeas,Chips,...,Potato,Rice,Sausage,Shampoo,Soap,Soda,Strawberry,Tomato,Water,Yogurt
0,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,1,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
29996,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
29997,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29998,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29999,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df=apriori(df,min_support=0.03,use_colnames=True)
#sets support value at 0.03 due to the large datset, support values are low

In [ ]:
df

      support                itemsets
0    0.136667                ( Apple)
1    0.138333               ( Banana)
2    0.140000                ( Beans)
3    0.135833                ( Bread)
4    0.136833               ( Butter)
..        ...                     ...
855  0.019500   ( Strawberry,  Water)
856  0.019767  ( Strawberry,  Yogurt)
857  0.018200       ( Tomato,  Water)
858  0.018267      ( Tomato,  Yogurt)
859  0.019333       ( Yogurt,  Water)

[860 rows x 2 columns]

In [ ]:
df_ar=association_rules(df,metric='confidence', min_threshold=0.2)
#sets the confidence threshold to 0.48; only associations with confidence > .48 are taken

In [ ]:
df_ar
#shows associations with a confidence level of 0.2 or above

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,( Butter),( Cereal),0.136833,0.207833,0.030300,0.221437,1.065456,0.001861,1.017473,0.071174
1,( Chips),( Cereal),0.136700,0.207833,0.030000,0.219459,1.055936,0.001589,1.014894,0.061361
2,( Cookie),( Cereal),0.138367,0.207833,0.030133,0.217779,1.047853,0.001376,1.012714,0.053002
3,( Ice Cream),( Cereal),0.142033,0.207833,0.030233,0.212861,1.024190,0.000714,1.006387,0.027529
4,( Juice),( Cereal),0.142300,0.207833,0.030200,0.212228,1.021144,0.000625,1.005578,0.024141
5,( Cereal),( Milk),0.207833,0.137267,0.076933,0.370168,2.696710,0.048405,1.369784,0.794249
6,( Milk),( Cereal),0.137267,0.207833,0.076933,0.560466,2.696710,0.048405,1.802289,0.729284
7,( Onion),( Cereal),0.135800,0.207833,0.030867,0.227295,1.093641,0.002643,1.025186,0.099078
8,( Soda),( Cereal),0.140567,0.207833,0.031100,0.221247,1.064542,0.001886,1.017225,0.070545

###3. Provide a few paragraphs interpreting the results for your boss (easy reading narration)

This analysis has 30000 retail transactions, after looking at we noticed some interesting connection between products that can help us to improve our business. The strongest link we found in data is between Cereal and Milk. When customer buys cereal there is 37% chance that they will also buy milk and when customer buy milk there is 56% chance that they will buy cereal. If we look at the lift value which is 2.7 shows that customers more likely to buy these items together.
However, if we look on other data they have connection like butter with cereal, chips with cereal, cookie with cereal, Juice with cereal, etc. but dont have as strong connection as we found in between cereal and milk and also if we look at the lift value which also close to 1. From the business perspective we can focus on the items which shows strong relations like milk and cereal. We can put them together or make some special offer like if you buy cereal and milk together is some percentage discount or online if someone buy milk suggest cereal.